//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KBJ_MessengerByTCP.LanguageResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language_res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language_res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KBJ_MessengerByTCP.LanguageResource.language_res", typeof(language_res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string strButtonClient {
            get {
                return ResourceManager.GetString("strButtonClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string strButtonConfirm {
            get {
                return ResourceManager.GetString("strButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string strButtonConfirmPortNumber {
            get {
                return ResourceManager.GetString("strButtonConfirmPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string strButtonServer {
            get {
                return ResourceManager.GetString("strButtonServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string strButtonToSendMessage {
            get {
                return ResourceManager.GetString("strButtonToSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached file of All message data, also saved at local .
        /// </summary>
        internal static string strEmailBody {
            get {
                return ResourceManager.GetString("strEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All message data of Messenger..
        /// </summary>
        internal static string strEmailSubject {
            get {
                return ResourceManager.GetString("strEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Server available with the given Information..
        /// </summary>
        internal static string strExceptionMessageConnectionRefusedAtEntrance {
            get {
                return ResourceManager.GetString("strExceptionMessageConnectionRefusedAtEntrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting of Message Data is Failed..
        /// </summary>
        internal static string strExceptionMessageDBInsertFailed {
            get {
                return ResourceManager.GetString("strExceptionMessageDBInsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port number is already in use..
        /// </summary>
        internal static string strExceptionMessagePortNumberAlreadyUsed {
            get {
                return ResourceManager.GetString("strExceptionMessagePortNumberAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Email with the Record is Failed..
        /// </summary>
        internal static string strExceptionMessageSendingEmailFailed {
            get {
                return ResourceManager.GetString("strExceptionMessageSendingEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address?.
        /// </summary>
        internal static string strLabelIPAddress {
            get {
                return ResourceManager.GetString("strLabelIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number?.
        /// </summary>
        internal static string strlabelPortNumber {
            get {
                return ResourceManager.GetString("strlabelPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username?.
        /// </summary>
        internal static string strLabelUserName {
            get {
                return ResourceManager.GetString("strLabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection with Server is removed..
        /// </summary>
        internal static string strMessageToNotifyClientIsDisconnectedFromServer {
            get {
                return ResourceManager.GetString("strMessageToNotifyClientIsDisconnectedFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to joined at this chat..
        /// </summary>
        internal static string strMessageToNotifyClientJoinedServer {
            get {
                return ResourceManager.GetString("strMessageToNotifyClientJoinedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left from this chat..
        /// </summary>
        internal static string strMessageToNotifyClientLeftServer {
            get {
                return ResourceManager.GetString("strMessageToNotifyClientLeftServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is closed..
        /// </summary>
        internal static string strMessageToNotifyServerIsClosed {
            get {
                return ResourceManager.GetString("strMessageToNotifyServerIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is ready....
        /// </summary>
        internal static string strMessageToNotifyServerIsOpened {
            get {
                return ResourceManager.GetString("strMessageToNotifyServerIsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message data is saved as a xml file at Desktop.
        /// </summary>
        internal static string strMessageToNotifyXmlFileIsSavedAt {
            get {
                return ResourceManager.GetString("strMessageToNotifyXmlFileIsSavedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Port Number.
        /// </summary>
        internal static string strMessageToValidatePortNumber {
            get {
                return ResourceManager.GetString("strMessageToValidatePortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type All Required Information to find Server..
        /// </summary>
        internal static string strMessageToValidateRequiredInfoToConnectServer {
            get {
                return ResourceManager.GetString("strMessageToValidateRequiredInfoToConnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string strSentTime {
            get {
                return ResourceManager.GetString("strSentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string strServerManager {
            get {
                return ResourceManager.GetString("strServerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance At Client.
        /// </summary>
        internal static string strTitleEntryForClient {
            get {
                return ResourceManager.GetString("strTitleEntryForClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance At Server.
        /// </summary>
        internal static string strTitleEntryForServer {
            get {
                return ResourceManager.GetString("strTitleEntryForServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger (Guest).
        /// </summary>
        internal static string strTitleForClientMessenger {
            get {
                return ResourceManager.GetString("strTitleForClientMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger (Owner).
        /// </summary>
        internal static string strTitleForServerMessenger {
            get {
                return ResourceManager.GetString("strTitleForServerMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose What You Want.
        /// </summary>
        internal static string strTitleMainWindow {
            get {
                return ResourceManager.GetString("strTitleMainWindow", resourceCulture);
            }
        }
    }
}
